name: java-ci-main
on:
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: "17"
        distribution: "temurin"
        cache: "maven"
    - name: Verify with Maven
      run: mvn --update-snapshots --batch-mode verify
  check-duplicates:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.kotlin-script.outputs }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: "17"
        distribution: "temurin"
        cache: "maven"
    - name: Build Jar
      run: mvn jar:jar
    - name: Get Jar name
      id: jar-name
      run: echo "jar_name=$(mvn help:evaluate -Dexpression=project.build.finalName -q -DforceStdout)" >> $GITHUB_OUTPUT
    - name: run kotlin script
      id: kotlin-script
      run: kotlinc -script ./check-duplicates.kts >> "$GITHUB_OUTPUT"
      env:
        JAR_PATH: ${{ github.workspace }}/target/${{ steps.jar-name.outputs.jar_name }}

  comment:
    needs: check-duplicates
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: "${{needs.check-duplicates.outputs.kotlin-script}}"
          })
