name: java-ci-main
on:
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: "17"
        distribution: "temurin"
        cache: "maven"
    - name: Verify with Maven
      run: mvn --update-snapshots --batch-mode verify
  compare-duplicates:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current branch
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Run duplicate check test on current branch
      run: |
        mvn test -Dtest=DuplicatedUnitsTest#getDuplicateConversions
        mkdir -p output/current_branch
        cp -r target/surefire-reports output/current_branch

    - name: Checkout master branch
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Run specific test on master branch
      run: |
        mvn test -Dtest=DuplicatedUnitsTest#getDuplicateConversions
        mkdir -p output/master_branch
        cp -r target/surefire-reports output/master_branch

    - name: Compare outputs
      run: |
        diff -r output/current_branch output/master_branch > diff.txt || true
        if [ -s diff.txt ]; then
          echo "Differences found:"
          cat diff.txt
          exit 1
        else
          echo "No differences found"
        fi
